Repository demokratie-live/democracy-server, pull requests merged in 2019-02, with the labels that each got.

#130 Alpha/master
  CHANGELOG.md
  src/config/procedureStates.js
  src/express/webhooks/debug/pushNotifications.js
  src/graphql/resolvers/Procedure.js
  src/graphql/schemas/Procedure.js
  src/services/notifications/index.js
Labels: #Bug, #Enhancement

#131 Internal/wom+package upgrades
  .env.example
  package.json
  src/config/constants.js
  src/config/db.js
  src/graphql/queries/getDeputyUpdates.js
  src/graphql/resolvers/Deputy.js
  src/graphql/resolvers/Procedure.js
  src/graphql/resolvers/Vote.js
  src/graphql/schemas/Deputy.js
  src/graphql/schemas/Procedure.js
  src/graphql/schemas/Vote.js
  src/importer/importDeputyProfiles.js
  src/index.js
  src/migrations/1-sms-verification.js
  src/migrations/2-geographical-urn-book.js
  src/models/Deputy.js
  src/models/Procedure.js
  src/models/Schemas/DeputyContact.js
  src/models/Schemas/DeputyLink.js
  src/models/Vote.js
  src/scripts/webhook.js
  yarn.lock
Labels: #Feature

#128 2019/sprint#3/voyager
  .env.example
  package.json
  src/config/constants.js
  src/index.js
  yarn.lock
Labels: #Enhancement
